# Generated by Django 2.2.1 on 2019-05-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('program', models.TextField(max_length=250)),
                ('adm_no', models.CharField(max_length=20)),
                ('dob', models.DateField(default=None)),
            ],
        ),
    ]
